<?php

return [
    'name' => 'plugins/affiliate-pro::affiliate.email.title',
    'description' => 'plugins/affiliate-pro::affiliate.email.description',
    'templates' => [
        'affiliate-application-approved' => [
            'title' => 'plugins/affiliate-pro::affiliate.email.affiliate_application_approved_title',
            'description' => 'plugins/affiliate-pro::affiliate.email.affiliate_application_approved_description',
            'subject' => 'plugins/affiliate-pro::affiliate.email.affiliate_application_approved_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/affiliate-pro::affiliate.email.customer_name',
                'affiliate_code' => 'plugins/affiliate-pro::affiliate.email.affiliate_code',
                'affiliate_dashboard_url' => 'plugins/affiliate-pro::affiliate.email.affiliate_dashboard_url',
                'commission_rate' => 'plugins/affiliate-pro::affiliate.email.commission_rate',
                'site_title' => 'plugins/affiliate-pro::affiliate.email.site_title',
            ],
        ],
        'affiliate-application-rejected' => [
            'title' => 'plugins/affiliate-pro::affiliate.email.affiliate_application_rejected_title',
            'description' => 'plugins/affiliate-pro::affiliate.email.affiliate_application_rejected_description',
            'subject' => 'plugins/affiliate-pro::affiliate.email.affiliate_application_rejected_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/affiliate-pro::affiliate.email.customer_name',
                'rejection_reason' => 'plugins/affiliate-pro::affiliate.email.rejection_reason',
                'site_title' => 'plugins/affiliate-pro::affiliate.email.site_title',
            ],
        ],
        'affiliate-application-submitted' => [
            'title' => 'plugins/affiliate-pro::affiliate.email.affiliate_application_submitted_title',
            'description' => 'plugins/affiliate-pro::affiliate.email.affiliate_application_submitted_description',
            'subject' => 'plugins/affiliate-pro::affiliate.email.affiliate_application_submitted_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/affiliate-pro::affiliate.email.customer_name',
                'customer_email' => 'plugins/affiliate-pro::affiliate.email.customer_email',
                'application_date' => 'plugins/affiliate-pro::affiliate.email.application_date',
                'admin_dashboard_url' => 'plugins/affiliate-pro::affiliate.email.admin_dashboard_url',
                'site_title' => 'plugins/affiliate-pro::affiliate.email.site_title',
            ],
        ],
        'affiliate-commission-earned' => [
            'title' => 'plugins/affiliate-pro::affiliate.email.affiliate_commission_earned_title',
            'description' => 'plugins/affiliate-pro::affiliate.email.affiliate_commission_earned_description',
            'subject' => 'plugins/affiliate-pro::affiliate.email.affiliate_commission_earned_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/affiliate-pro::affiliate.email.customer_name',
                'commission_amount' => 'plugins/affiliate-pro::affiliate.email.commission_amount',
                'order_id' => 'plugins/affiliate-pro::affiliate.email.order_id',
                'order_total' => 'plugins/affiliate-pro::affiliate.email.order_total',
                'commission_status' => 'plugins/affiliate-pro::affiliate.email.commission_status',
                'commission_date' => 'plugins/affiliate-pro::affiliate.email.commission_date',
                'affiliate_dashboard_url' => 'plugins/affiliate-pro::affiliate.email.affiliate_dashboard_url',
                'current_balance' => 'plugins/affiliate-pro::affiliate.email.current_balance',
                'site_title' => 'plugins/affiliate-pro::affiliate.email.site_title',
            ],
        ],
        'affiliate-withdrawal-requested' => [
            'title' => 'plugins/affiliate-pro::affiliate.email.affiliate_withdrawal_requested_title',
            'description' => 'plugins/affiliate-pro::affiliate.email.affiliate_withdrawal_requested_description',
            'subject' => 'plugins/affiliate-pro::affiliate.email.affiliate_withdrawal_requested_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/affiliate-pro::affiliate.email.customer_name',
                'customer_email' => 'plugins/affiliate-pro::affiliate.email.customer_email',
                'withdrawal_amount' => 'plugins/affiliate-pro::affiliate.email.withdrawal_amount',
                'withdrawal_method' => 'plugins/affiliate-pro::affiliate.email.withdrawal_method',
                'request_date' => 'plugins/affiliate-pro::affiliate.email.request_date',
                'admin_dashboard_url' => 'plugins/affiliate-pro::affiliate.email.admin_dashboard_url',
                'site_title' => 'plugins/affiliate-pro::affiliate.email.site_title',
            ],
        ],
        'affiliate-withdrawal-approved' => [
            'title' => 'plugins/affiliate-pro::affiliate.email.affiliate_withdrawal_approved_title',
            'description' => 'plugins/affiliate-pro::affiliate.email.affiliate_withdrawal_approved_description',
            'subject' => 'plugins/affiliate-pro::affiliate.email.affiliate_withdrawal_approved_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/affiliate-pro::affiliate.email.customer_name',
                'withdrawal_amount' => 'plugins/affiliate-pro::affiliate.email.withdrawal_amount',
                'withdrawal_method' => 'plugins/affiliate-pro::affiliate.email.withdrawal_method',
                'processing_date' => 'plugins/affiliate-pro::affiliate.email.processing_date',
                'transaction_id' => 'plugins/affiliate-pro::affiliate.email.transaction_id',
                'affiliate_dashboard_url' => 'plugins/affiliate-pro::affiliate.email.affiliate_dashboard_url',
                'remaining_balance' => 'plugins/affiliate-pro::affiliate.email.remaining_balance',
                'site_title' => 'plugins/affiliate-pro::affiliate.email.site_title',
            ],
        ],
        'affiliate-withdrawal-rejected' => [
            'title' => 'plugins/affiliate-pro::affiliate.email.affiliate_withdrawal_rejected_title',
            'description' => 'plugins/affiliate-pro::affiliate.email.affiliate_withdrawal_rejected_description',
            'subject' => 'plugins/affiliate-pro::affiliate.email.affiliate_withdrawal_rejected_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/affiliate-pro::affiliate.email.customer_name',
                'withdrawal_amount' => 'plugins/affiliate-pro::affiliate.email.withdrawal_amount',
                'withdrawal_method' => 'plugins/affiliate-pro::affiliate.email.withdrawal_method',
                'rejection_reason' => 'plugins/affiliate-pro::affiliate.email.rejection_reason',
                'rejection_date' => 'plugins/affiliate-pro::affiliate.email.rejection_date',
                'affiliate_dashboard_url' => 'plugins/affiliate-pro::affiliate.email.affiliate_dashboard_url',
                'current_balance' => 'plugins/affiliate-pro::affiliate.email.current_balance',
                'site_title' => 'plugins/affiliate-pro::affiliate.email.site_title',
            ],
        ],
        'affiliate-digest' => [
            'title' => 'plugins/affiliate-pro::affiliate.email.affiliate_digest_title',
            'description' => 'plugins/affiliate-pro::affiliate.email.affiliate_digest_description',
            'subject' => 'plugins/affiliate-pro::affiliate.email.affiliate_digest_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/affiliate-pro::affiliate.email.customer_name',
                'period_start' => 'plugins/affiliate-pro::affiliate.email.period_start',
                'period_end' => 'plugins/affiliate-pro::affiliate.email.period_end',
                'total_clicks' => 'plugins/affiliate-pro::affiliate.email.total_clicks',
                'conversion_rate' => 'plugins/affiliate-pro::affiliate.email.conversion_rate',
                'new_commissions_count' => 'plugins/affiliate-pro::affiliate.email.new_commissions_count',
                'earnings_this_week' => 'plugins/affiliate-pro::affiliate.email.earnings_this_week',
                'current_balance' => 'plugins/affiliate-pro::affiliate.email.current_balance',
                'top_products' => 'plugins/affiliate-pro::affiliate.email.top_products',
                'traffic_sources' => 'plugins/affiliate-pro::affiliate.email.traffic_sources',
                'tips' => 'plugins/affiliate-pro::affiliate.email.tips',
                'affiliate_dashboard_url' => 'plugins/affiliate-pro::affiliate.email.affiliate_dashboard_url',
                'site_title' => 'plugins/affiliate-pro::affiliate.email.site_title',
            ],
        ],
        'affiliate-banned' => [
            'title' => 'plugins/affiliate-pro::affiliate.email.affiliate_banned_title',
            'description' => 'plugins/affiliate-pro::affiliate.email.affiliate_banned_description',
            'subject' => 'plugins/affiliate-pro::affiliate.email.affiliate_banned_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/affiliate-pro::affiliate.email.customer_name',
                'customer_email' => 'plugins/affiliate-pro::affiliate.email.customer_email',
                'site_title' => 'plugins/affiliate-pro::affiliate.email.site_title',
            ],
        ],
        'affiliate-unbanned' => [
            'title' => 'plugins/affiliate-pro::affiliate.email.affiliate_unbanned_title',
            'description' => 'plugins/affiliate-pro::affiliate.email.affiliate_unbanned_description',
            'subject' => 'plugins/affiliate-pro::affiliate.email.affiliate_unbanned_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/affiliate-pro::affiliate.email.customer_name',
                'customer_email' => 'plugins/affiliate-pro::affiliate.email.customer_email',
                'affiliate_dashboard_url' => 'plugins/affiliate-pro::affiliate.email.affiliate_dashboard_url',
                'site_title' => 'plugins/affiliate-pro::affiliate.email.site_title',
            ],
        ],
    ],
];
